language: node_js
node_js:
  - 4
  - 5
matrix:
  allow_failures:
    - node_js: 5
# NodeJS v4 requires gcc 4.8
env:
  - NODE_ENV=travis CXX="g++-4.8" CC="gcc-4.8"
services:
  - mongodb
sudo: false
# gcc 4.8 requires ubuntu-toolchain-r-test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
    - clang
before_install:
  - gem update --system
  - npm i nsp -g
after_script:
  - nsp audit-package
cache:
  apt: true
  directories:
    - node_modules/
    - public/lib/
notifications:
  slack:
    secure: XRMYG9Hf+bJjMSHHXN0XeGT4ZhSP+oCHBUWmjBwxO0p+VORBOEZvlh/2OvxingFuzLGOXFeOPr1g91G+OgiCGR6GxaDpf680lEjk8ESTJ4oECv0aO2NQEZWYR4peiLRtBmJZTCSsKXDY21nrDHiKOaMQyPJqbzkIrTBMnK/YJpg=
