---

- name: install, configure and enable influxdb
  import_tasks: influxdb.yml
  tags: influxdb


- name: install let's encrypt's certbot
  import_tasks: certbot.yml
  tags: ssl


- name: configure and enbale nginx
  import_tasks: nginx.yml
  tags: nginx


- name: install and configure mongodb
  import_tasks: mongodb.yml
  tags: mongodb


- name: Clone/pull project repo
  git:
    repo: https://github.com/trustroots/trustroots.git
    dest: "{{ tr_dir }}"
    force: yes
    version: "{{ version | default('HEAD') }}"
## this is currently not needed as node.yml restarts the server on every runn anyways
#  notify:
#    - restart all pm2 processes
  tags:
    - git


- name: "chown {{ tr_dir }} {{ tr_user }}"
  file:
    dest: "{{ tr_dir }}"
    owner: "{{ tr_user }}"
    group: "{{ tr_user }}"
    mode: "u=rwX,g=rX,o=rX"
    recurse: yes
  tags:
    - chown

    
- name: install and configure node
  import_tasks: node.yml
  tags: node


- name: install and configure grafana
  import_tasks: grafana.yml
  tags: grafana

